// <auto-generated />
namespace RecruitAgency.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Recruitment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Recruitment));
        
        string IMigrationMetadata.Id
        {
            get { return "201611070029358_Recruitment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
